Add Synchronous versions of the Format commands
mhartington/formatter.nvim pull request #109
Opened 2021-12-22 13:27 UTC by itmecho

Implements #108 

Adds synchronous versions of the existing `Format` commands.

I've also added a commit which changes the format function to accept a table of options instead of a series of boolean. This should make it easier to extend in the future but I'm happy to revert it if it's not wanted!

2021-12-23 08:38 UTC, lukas-reineke requested changes
otherwise LGTM
thanks

2021-12-23 09:26 UTC, itmecho commented on lua/formatter/format.lua
> +  local sync = opts.sync or false
Nice, that's much cleaner!

2021-12-23 11:18 UTC, lukas-reineke commented on lua/formatter/format.lua
> +	local job_id = nil
there is a tab character here :eyes: 

we should probably require a formatter :sweat_smile:

2021-12-23 12:38 UTC, itmecho commented on lua/formatter/format.lua
> +	local job_id = nil
Ugh I thought I got them all! Which formatter/config are you using?

2021-12-23 12:43 UTC, itmecho commented on lua/formatter/format.lua
> +	local job_id = nil
Fixed this in the latest commit. I failed to use the `opts` table after making your previous change!

2021-12-24 01:58 UTC, lukas-reineke commented on lua/formatter/format.lua
> +	local job_id = nil
> Which formatter/config are you using?

There is nothing enforced. But I think we should change that.

2021-12-24 01:58 UTC, lukas-reineke approved these changes

2022-02-08 16:39 UTC, mhartington commented
I think splitting this PR into two features would be best here. 

1) changings the options to be a table
2) Potentially a sync version.

Though, I'm on the fence about adding a sync version. The whole point of this plugin is to be async, so adding a synchronous command seems like a step backwards.

2022-02-09 21:31 UTC, mjlbach commented
Another option to "sync" is to set the buffer to be not modifiable while await the result of the formatter, that doesn't block the editor and prevents users from inadvertantly modifying the buffer.

2022-02-21 10:50 UTC, itmecho commented
> I think splitting this PR into two features would be best here.
> 
>     1. changings the options to be a table
> 
>     2. Potentially a sync version.
> 
> 
> Though, I'm on the fence about adding a sync version. The whole point of this plugin is to be async, so adding a synchronous command seems like a step backwards.

Fine by me! On the sync command, I think it would be nice to provide the option for people but at the end of the day it's your project. I can always maintain a fork for myself that adds it if you don't think supporting it is the right thing to do

2022-02-21 12:47 UTC, itmecho commented
Opened #122 for the `opts` table improvement

2022-02-21 13:01 UTC, itmecho commented
I have a branch based on the one from #122 which adds the sync support. I can either create a PR for it or if you don't think you want that functionality I can maintain it on my fork. Let me know which you'd prefer!

2022-02-21 13:23 UTC, itmecho commented
I also have a branch which handles @mjlbach's proposal in case you think that's a better option!

2022-03-29 14:17 UTC, mhartington commented
Hey @itmecho! Sorry about the delay on my end (life, am I right?)

I'd like to get this merged in, so if you have a branch that uses what @mjlbach has suggested, let's get that up and merge in!

2022-03-29 15:51 UTC, itmecho commented
> Hey @itmecho! Sorry about the delay on my end (life, am I right?)

No worries! I have 2 young kids so I fully understand that!

> I'd like to get this merged in, so if you have a branch that uses what @mjlbach has suggested, let's get that up and merge in!

Brilliant! I'll create a PR when I'm back at my PC =]

2022-05-12 21:51 UTC, Hrle97 commented
Can we close this in favor of #131?

2022-07-30 12:44 UTC, Hrle97 commented
Closing in favor of #175

2022-07-30 12:44 UTC, closed without merging