Add sh filetype with shfmt formatter.
mhartington/formatter.nvim pull request #171
Opened 2022-07-24 11:41 UTC by WIttyJudge

It was inspired by [neoformat formatter for sh](https://github.com/sbdchd/neoformat/blob/master/autoload/neoformat/formatters/sh.vim)
To test it you need to install ``shfmt``, then create any sh or bash file.
E.g. I tested this on my own local script, copy-paste this.

```sh
#!/usr/bin/env bash

# Extract archives - use: extract <file>

help() {
echo "Usage: extract [file]

Available file formats:
  .tar
  .tar.bz2
  .tar.gz
  .tbz2
  .tgz
  .bz2
  .rar
  .gz
  .zip
  .Z
  .7z"
}

if [ -f "$1" ] ; then
  case "$1" in
    *.tar) tar xvf "$1" ;;
    *.tar.bz2) tar xvjf "$1" ;;
    *.tar.gz) tar xvzf "$1" ;;
    *.tbz2) tar xvjf "$1" ;;
    *.tgz) tar xvzf "$1" ;;
    *.bz2) bunzip2 "$1" ;;
    *.rar) rar x "$1" ;;
    *.gz) gunzip "$1" ;;
    *.zip) unzip "$1" ;;
    *.Z) uncompress "$1" ;;
    *.7z) 7z x "$1" ;;
    *) echo "'$1' cannot be extracted via extract()" && help ;;
  esac
else
    help
fi
```

2022-07-30 12:37 UTC, Hrle97 commented
This is a very nice find! Thank you :smile:

2022-07-30 12:40 UTC, Hrle97 requested changes
please just change `_value` to `vim.opt:get()` and I'll merge

2022-07-30 12:40 UTC, Hrle97 commented on lua/formatter/filetypes/sh.lua
> +  local shiftwidth = vim.opt.shiftwidth._value
`_value` is private - you should use `vim.opt:get()`

2022-08-03 19:51 UTC, WIttyJudge commented
Changed. Do you see this?

2022-08-04 20:25 UTC, Hrle97 commented
yes thank you :)

2022-08-04 20:25 UTC, merged