[FORMAT] Allow user to provide an optional cwd function
mhartington/formatter.nvim pull request #58
Opened 2021-07-11 14:14 UTC by jameswalmsley

Most formatters will move up the directory tree to find their nearest
parent for configuration and apply that style.

2021-07-12 00:58 UTC, lukas-reineke requested changes

2021-07-12 00:58 UTC, lukas-reineke commented on lua/formatter/format.lua
> +      cwd = current.config.cwd()
You don't have to make `cwd` a function
The whole formatter option is already a function that gets evaluated on each run. (line 27)
Just pass `cwd` through directly.

Then you can do this on the user side
```lua
require("formatter").setup(
    {
        filetype = {
            foo = {
                function()
                    return {
                        exe = "foo",
						cwd = vim.fn.expand("%:p:h")
                    }
                end
            }
        }
    }
)
```

2021-07-12 08:28 UTC, jameswalmsley commented on lua/formatter/format.lua
> +      cwd = current.config.cwd()
Nice.
Updated PR.

2021-07-12 08:47 UTC, lukas-reineke approved these changes
LGTM

maybe we can add something in the readme as well

thanks for this :+1:

2021-07-12 10:03 UTC, jameswalmsley commented
@lukas-reineke I've updated the documentation, let me know if you want me to change anything or clarify it.

2021-07-12 16:36 UTC, mhartington requested changes

2021-07-12 16:36 UTC, mhartington commented on lua/formatter/format.lua
> +        cwd = current.config.cwd,
This seems like it will fail if cwd is not passed by the formatter. There should be something like

```
cwd = current.config.cwd or vim.fn.getcwd()
```

Not every tool needs a cwd to be passed in.

2021-07-12 17:43 UTC, jameswalmsley commented on lua/formatter/format.lua
> +        cwd = current.config.cwd,
I've actually tested this and if cwd is nil then jobstart uses the vim cwd by default.. so the code doesn't crash and other configs don't need to set it.

I'll add a commit with `or vim.fn.cwd()` then the code will look more explicit.

Give me shout if you think it's unnecessary in the end.

2021-07-12 20:47 UTC, mhartington commented on lua/formatter/format.lua
> +        cwd = current.config.cwd,
Better to be explicit in case future releases changes this.

2021-07-12 21:58 UTC, jameswalmsley commented
@mhartington I've updated the PR with an explicit default.

2021-07-14 13:28 UTC, jameswalmsley commented
@lukas-reineke @mhartington You happy with this PR? I'd like to get it merged so I can merge a PR on LunarVim.

2021-07-14 13:31 UTC, closed without merging

2021-07-14 13:32 UTC, mhartington commented
Added. Thanks for the PR!

2021-07-14 14:14 UTC, jameswalmsley commented
Awesome. Many thanks 😊